config/routes.rb
Rails.application.routes.draw do

devise_for :admins, controllers: { registrations: "admins/registrations" }
  devise_for :users, controllers: { registrations: "users/registrations" }
  root to: 'application#index'
  resources :categories, only: [:index, :show]
  resources :products#, only: [:index, :show]

post '/cart_products/product/:id', to: 'cart_products#add_product', as: "add_product"

get '/user/cart', to: 'cart_products#show_cart', as: "show_cart"

post '/user/cart/:id', to: 'cart_products#remove_product', as: "remove_product"

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  after_create :create_cart
  has_one :cart

  def create_cart
    Cart.create(user_id: id)
  end
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  belongs_to :user
  has_many :cart_products, foreign_key: "cart_id"
  has_many :products, through: :cart_products
end

app/models/cart_product.rb
class CartProduct < ActiveRecord::Base
  belongs_to :cart
  belongs_to :product
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category
  has_many :cart_products, foreign_key: "product_id"
  has_many :carts, through: :cart_products
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  after_create :create_cart
  has_one :cart

  def create_cart
    Cart.create(user_id: id)
  end

end

app/controllers/admins/sessions_controller.rb
class Admins::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/admins/unlocks_controller.rb
class Admins::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  before_filter :authenticate_admin!
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include ApplicationHelper

end

app/controllers/cart_products_controller.rb
class CartProductsController < ApplicationController

  def add_product
    @cart = current_user.cart
    @product = Product.find(params[:id])
    @cart.products << @product
    redirect_to show_cart_path
  end

  def show_cart
    @product = current_user.cart.products
    total
  end

  def total
    price_array = current_user.cart.products.map(&:price)
    if price_array.empty?
       @total = 0
    else
       @total = price_array.reduce(:+).round(2)
    end
     @total
  end

  def remove_product
    @cart = current_user.cart
    order = @cart.cart_products.where(product_id: params[:id]).first
    order.delete
    redirect_to show_cart_path
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def show
    @cart = Cart.find(current_user)
  end


end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    unless is_admin?
      render status: 403, text: "Permission Denied"
    else
       @products = Product.all
    end
  end

  def show
    @product = Product.find(params[:id])
  end

  def edit
    unless is_admin?
      render status: 403, text: "Permission Denied"
    else
    @product = Product.find(params[:id])
    end
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      redirect_to products_path
    else
      redirect_to edit_product
    end
  end

  def destroy
    @product = Product.destroy(params[:id])
    redirect_to products_path
  end

  def new
    unless is_admin?
      render status: 403, text: "Permission Denied"
    else
    @product = Product.new
    end
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to products_path
    else
      redirect_to new_product
    end
  end

  private
  def product_params
    params.require(:product).permit(:name, :description, :price, :image_url, :category_id)
  end

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def is_admin?
    current_user && current_user.admin
  end
end

app/helpers/cart_products_helper.rb
module CartProductsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/categories/index.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
<title>GrumpyShop</title>

</head>

<body>

    <div class="container">

        <header class="jumbotron jumbo-index">
            <h1>Categories</h1>
            </h3>
        </header>

        <hr>

        <div class="row text-center">

            <% @categories.each do |category| %>
                <div class="col-md-3 col-sm-6 hero-feature">
                    <div class="thumbnail">
                        <%= link_to category_path(category), class:"links" do %>
                        <img class="links" src="https://scontent-sjc2-1.xx.fbcdn.net/hphotos-xta1/v/t1.0-9/11391342_867507243285014_6569955569849357941_n.jpg?oh=90f21ce05f2073d730c642745b55533f&oe=562F8BFB" alt="">
                        <div class="caption">
                            <h3><%=category.name%></h3>
                        <% end %>
                                <p><%= link_to'View Products!', category_path(category), class:"btn btn-primary links"%>
                            </p>
                        </div>
                    </div>
                </div>
            <% end %>
        </div>
        <hr>

</body>
</html>

app/views/categories/show.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
<title>GrumpyShop</title>
</head>
<body>

    <div class="container">

        <header class="jumbotron hero-spacer">
            <h1><%=@category.name%></h1>
        </header>
        <hr>

        <div class="row text-center">

            <%@category.products.each do |product| %>
                <div class="col-md-3 col-sm-6 hero-feature">
                    <%= link_to product_path(product), class:"links" do %>
                    <div class="thumbnail">
                        <img class="links" src="<%= product.image_url %>" alt="" class="img_resize">
                        <div class="caption">
                            <h3><%=product.name%></h3>
                            <p>
                    <% end %>
                            <a><%= link_to'More Info', product_path(product), class:"btn btn-primary links"%></a>
                            </p>
                        </div>
                    </div>
                </div>
            <% end %>
        </div>

        <hr>
</body>
</html>